"""create_initial_tables

Revision ID: e201dec3ffad
Revises: 08ff9bc547a3
Create Date: 2026-05-13 02:54:04.841655

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e201dec3ffad"
down_revision: str | Sequence[str] | None = "08ff9bc547a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.String(length=64),
            nullable=False,
            comment="One of: nasa_payload_guide, casis_solicitation, iss_annual_report, paper, hardware_spec, regulatory",
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("organization", sa.String(length=128), nullable=True),
        sa.Column(
            "raw_path", sa.Text(), nullable=False, comment="Local or S3 path to the original file"
        ),
        sa.Column(
            "checksum",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hex digest of the raw file",
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "doc_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checksum", name="uq_documents_checksum"),
    )
    op.create_index(
        "idx_documents_metadata",
        "documents",
        ["doc_metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_documents_source_type", "documents", ["source_type"], unique=False)
    op.create_table(
        "eval_examples",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "query_intent",
            sa.String(length=64),
            nullable=True,
            comment="One of: hardware_lookup, safety_precedent, protocol_adaptation, mission_integration, regulatory_pathway",
        ),
        sa.Column("expected_chunk_ids", sa.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column("expected_documents", sa.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column(
            "expected_keywords",
            sa.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Fallback for examples without chunk-level ground truth",
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "per_example_results",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section_path", sa.Text(), nullable=True),
        sa.Column(
            "chunk_type",
            sa.String(length=32),
            server_default="text",
            nullable=False,
            comment="One of: text, table, figure_caption",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            nullable=True,
            comment="Null until embedded; populated by ingestion pipeline",
        ),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column(
            "chunk_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_chunks_doc_index"),
    )
    op.create_index("idx_chunks_document", "chunks", ["document_id"], unique=False)
    op.create_index(
        "idx_chunks_embedding",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "idx_chunks_metadata", "chunks", ["chunk_metadata"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "idx_chunks_tsv", "chunks", ["content_tsv"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_chunks_tsv", table_name="chunks", postgresql_using="gin")
    op.drop_index("idx_chunks_metadata", table_name="chunks", postgresql_using="gin")
    op.drop_index(
        "idx_chunks_embedding",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("idx_chunks_document", table_name="chunks")
    op.drop_table("chunks")
    op.drop_table("eval_runs")
    op.drop_table("eval_examples")
    op.drop_index("idx_documents_source_type", table_name="documents")
    op.drop_index("idx_documents_metadata", table_name="documents", postgresql_using="gin")
    op.drop_table("documents")
    # ### end Alembic commands ###
